apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: enhancementWorkload-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enhancementWorkload-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "enhancementWorkload.serviceAccountName" . }}
    namespace: {{ include "enhancementWorkload.namespace" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enhancementWorkload-cluster-role
rules:
  - apiGroups:
      - apps.kruise.io
    resources:
      - clonesets
      - clonesets/status
      - sidecarsets
      - sidecarsets/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch